### PR TITLE
Ansible scripts

### PR DESCRIPTION
**Pull request by fgiorgetti**

### CODE REVIEW

**Review by pwright — COMMENTED** [review]
There seem to be a few things in this PR besides 'ansible':
- Removal of skewer for CI and readme generation
- Adding circleci for CI
- Adding/splitting of k8s/podman hello world

Given that podman is a preview feature, is it too early to introduce it into the 'one getting started'?
cc @ssorj

**Comment by fgiorgetti** [comment]
> * Removal of skewer for CI and readme generation

Not sure if we need/want to replace skewer at this point.

> * Adding circleci for CI

If we intend to use these Ansible scripts for CI as well, we have to keep using Github Actions,
as we cannot run Podman v4 on CircleCI yet (afaik).

**Comment by ssorj** [comment]
Something doesn't look right about this.  I see the "skupper connection-token" command.  We no longer support this.  I think this is rebased on the wrong thing.

**Comment by fgiorgetti** [comment]
> Something doesn't look right about this. I see the "skupper connection-token" command. We no longer support this. I think this is rebased on the wrong thing.

Rebased on top of main branch.

**Review by grs — APPROVED** [review]

**Review by pwright — COMMENTED** [review]
I'm worried that this demo would be lost in this repo and feel that it might be better if:
- we created a skupper-example-ansible repo
- link to the new repo from the readme in hello world
- link to the new repo from https://skupper.io/examples/index.html
- link from the new repo to other examples that live in https://github.com/skupperproject/skupper-ansible/tree/main/examples/

**Comment by fgiorgetti** [comment]
@ssorj @ajssmith could you please try it again?


> I'm worried that this demo would be lost in this repo and feel that it might be better if:
> 
> we created a skupper-example-ansible repo
> link to the new repo from the readme in hello world
> link to the new repo from https://skupper.io/examples/index.html
> link from the new repo to other examples that live in https://github.com/skupperproject/skupper-ansible/tree/main/examples/

@pwright Creating the skupper-example-ansible repo works, but maybe it would be simpler just to:

- Add ansible examples under each existing example (like this PR does and maybe it will really be quite hard to find)
OR
- As you said: "link from the new repo to other examples that live in https://github.com/skupperproject/skupper-ansible/tree/main/examples/"

But regardless of the approach we decided to go with, it might be interesting to drop a
reference to the ansible examples into https://skupper.io/examples as well as to each example
that has an ansible alternative somewhere.

**Comment by ssorj** [comment]
This is now covered with https://github.com/skupperproject/skupper-example-ansible, which is adapted from this PR.  Thanks, Fernando!

**Pull request closed without merging**
